# Generated by GitHub Copilot

param(
  [ValidateSet('up', 'down', 'restart', 'status', 'logs')]
  [string] $Command = 'up'
)

$scriptPath = '/mnt/c/VEREDAS/scripts/wsl-stacks.sh'

C:\Windows\System32\wsl.exe -d Ubuntu -- bash $scriptPath $Command