services:
  hub:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: hub
    restart: unless-stopped
    ports:
      - "${VEREDAS_PWA_HUB_PORT:-4400}:80"

  portal-aluno:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: portal-aluno
    restart: unless-stopped
    ports:
      - "${VEREDAS_PWA_PORTAL_ALUNO_PORT:-4401}:80"

  pwa-motorista:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: pwa-motorista
    restart: unless-stopped
    ports:
      - "${VEREDAS_PWA_MOTORISTA_PORT:-4402}:80"

  pwa-monitor:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: pwa-monitor
    restart: unless-stopped
    ports:
      - "${VEREDAS_PWA_MONITOR_PORT:-4403}:80"

  pwa-paciente:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: pwa-paciente
    restart: unless-stopped
    ports:
      - "${VEREDAS_PWA_PACIENTE_PORT:-4404}:80"